spring.application.name=careerpilot-backend

spring.datasource.url=jdbc:postgresql://ep-falling-star-at8z1xgi.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TkmU24eGdOpP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080